### ISSUE TITLE
Support Mixer telemetry reporting

### ISSUE THREAD

**Issue by esbie** [linkerd/linkerd#1410]
Mixer provides a [report api](https://istio.io/docs/reference/api/mixer/mixer-service.html#report) that linkerd can use to report logs and metrics.

- [x] #1398 Introduce Istio telemeter and Mixer client
- [x] #1413 use Mixer's global dictionary
- [ ] switch to using Mixer global dictionary on the server
- [x] #1435 wire up request filter
- [ ] export `source.uid`, deprecate `source.labels` and `target.labels`

**Comment by adleong** [comment]
Getting source.uid and target.uid is a bit tricky because linkerd is not running as a sidecar.  A couple options:

1.  For outgoing traffic, linkerd gets the remoteAddress of the request (ie source.ip).  Linkerd keeps a watch on the k8s API to keep a mapping of IP to pod name.  When this request reaches the incoming router of the destination linkerd, that linkerd looks at the remoteAddress of the response (ie target.ip) and uses its mapping to get the target.uid.  It encodes this as a header on the response it sends back to the source linkerd.  The source linkerd now has the source.uid and the target.uid.  
2. We run linkerd-tcp as a sidecar in addition to the linkerd which is run as a daemonset.  Since linkerd-tcp is running as a sidecar, it can get the pod name from the downward API.  The source linkerd-tcp can write the source.uid onto a request header and the target linkerd-tcp can write the target.uid onto a response header.  This gives the linkerds access to both pieces of information.

Option 1 requires each linked to keep an additional watch on the k8s api for the list of pods on its node.  To complicate things further, `remoteAddress` is not a field on response and we may need to make a finagle change to get access to this information. 

Option 2 is more complex since it requires both a sidecar linkerd-tcp and a daemonset linkerd (each request would make 5 hops from source app to destination app).  However, we may be moving in this direction anyway to have linkerd-tcp initiate and terminate TLS as a sidecar.  This option would require adding code in linkerd-tcp to read the environment variable and write the header.

**Comment by esbie** [comment]
I mentioned this last week, but the istio identifier needs to know source id and source tags too (for [MatchConditions](https://github.com/linkerd/linkerd/issues/1402)). So whichever solution we decide on here will be used by the identifier as well.
