### ISSUE TITLE
1.2.0 upgrade guide

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd#1624]
## New Features

- [x] ConfigMap interpreter (#1506)
- [x] DNS SRV namer (#1610)

## Breaking Changes
- [x] admin only listens on localhost by default
- [x] removed support for PKCS#1 keys (#1590)
- [x] `disableValidation: true` and `clientAuth` settings in client TLS configuration are incompatible (#1621)
- [x] possibly something to do with StatsD telemeter (see discussion on #1578)

## How to update your config

- [x] examples for new features
- [x] admin cfg
- [x] if you have PKCS1 keys....stop doing that......

**Comment by adleong** [comment]
https://buoyant.io/2017/09/08/linkerd-1-2-0-announcement-migration-guide/
